### ISSUE TITLE
hugegraph --url http://127.0.0.1:31495   报错 Invalid value of argument '--url': 'http://127.0.0.1:31495'

### ISSUE THREAD

**Issue by fisherinbox** [hugegraph/hugegraph-tools#10]
hugegraph --url http://127.0.0.1:8080 则不报错,难道还不支持其他端口吗,怎么能支持

更进一步想问的是,能否使用 hugegraph-tools来实现远程启动或关闭hugegraph server,比如这样 
bin/hugegraph --url http://192.168.1.1:8080 start-all -p /home/user/hugegraph-0.7.4 -v 0.7

**Comment by zhoney** [comment]
@fisherinbox --url参数中的端口使用9999以下的都可以。

hugegraph-tools目前不支持远程启动和关闭hugegraph server的功能。hugegraph-tools是通过RESTful API访问hugegraph server的，远程管理则需要涉及到互信和安全的问题。

另外，也可以自己写脚本实现远程启动或者关闭服务
