### ISSUE TITLE
compatible problem with new version of hugegraph studio

### ISSUE THREAD

**Issue by suesunss** [hugegraph/hugegraph-tools#16]
Hi，

我看到上个pr处理了`start-all.sh`中`start_hugegraph_studio()`函数中的配置文件名称不匹配问题，但是`deploy.sh`中也存在对studio配置文件的更改：

```
function config_hugegraph_studio() {
    local studio_server_conf="$STUDIO_DIR/conf/hugestudio.properties"

    write_property $studio_server_conf "server\.httpBindAddress" $IP
}
```

如上所示，默认会把属性写入到hugestudio.properties中。

另外，新版的hugegraph-stuido配置server ip和server port的属性名已经不是`server.httpBindAddress`和`server.httpPort`了，而是`studio.server.host`和`studio.server.port`。

**Comment by Linary** [comment]
@suesunss 上个pr确实是有遗漏之处，我们会尽快修正。
