### ISSUE TITLE
清除hbase后端数据问题

### ISSUE THREAD

**Issue by nohunt** [hugegraph/hugegraph-tools#22]
输入命令 ./hugegraph --url "xxx" graph-clear
报 The following option is required:[--confirm-message | -c]
输入命令 ./hugegraph --url "xxx" graph-clear -c 
报 Expected a value after paramter -c 

想知道,这个graph-clear 详细的使用方法，-c 后面还有接什么参数么？

**Comment by javeme** [comment]
确认消息是：`-c "I'm sure to delete all data"`

**Comment by nohunt** [comment]
> 确认消息是：`-c "I'm sure to delete all data"`

./hugegraph --url "xxx" graph-clear -c "I'm sure to delete all data".
不过还是出错，为是不去掉-c 的命令，而在用户输入回车，再加个确认输入呢？

**Comment by zhoney** [comment]
@nohunt 

`bin/hugegraph --url xxx graph-clear -c "I'm sure to delete all data"`
我验证过应该是可以的。请提供一下你的报错信息。

> 为是不去掉-c 的命令，而在用户输入回车，再加个确认输入呢？

这个是习惯问题，都可以

**Comment by nohunt** [comment]
> @nohunt
> 
> `bin/hugegraph --url xxx graph-clear -c "I'm sure to delete all data"`
> 我验证过应该是可以的。请提供一下你的报错信息。
> 
> > 为是不去掉-c 的命令，而在用户输入回车，再加个确认输入呢？
> 
> 这个是习惯问题，都可以

报错如下：
./bin/hugegraph: line 90 [: too many arguments
was passed main parameter 'sure' but no main parameter was defined in your arg class

**Comment by zhoney** [comment]
@nohunt 

> -c "I'm sure to delete all data"

confirm message加上双引号，就可以了
