### ISSUE TITLE
Error "Could not create the Java Virtual Machine" when trying init DB(Default conf,rockdb)

### ISSUE THREAD

**Issue by chrischeng021** [hugegraph/hugegraph-tools#25]
user@test:~/hugegraph/hugegraph-0.8.0$ ./bin/init-store.sh
Initing HugeGraph Store...
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

user@test:~/hugegraph/hugegraph-0.8.0$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**Comment by javeme** [comment]
@chrischeng021 We generally use java 8, of course java 9 should also be compatible, maybe you can try to use OpenJDK 9 GA version (please refer to https://github.com/elastic/elasticsearch/issues/28780 )

**Comment by chrischeng021** [comment]
@javeme Hi, I've just updated my java version, but when I start the init-store.sh script, I still get the same error.... Here are the details:

bash-4.2# java -version
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)

bash-4.2# ./bin/init-store.sh
Initing HugeGraph Store...
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by javeme** [comment]
@chrischeng021 It looks like an environmental issue. Could you try using Java 8 or other machines?

**Comment by chrischeng021** [comment]
@javeme Actually I've tried 3 different servers and my local laptop, but all the same problem, and about the Java version, I've tried from openJDK 9ga to openJDK11, also the oracle jdk9, but none of them works.....

**Comment by javeme** [comment]
@chrischeng021 Is there something wrong during the operation? Please confirm that you are using the correct JDK via `java -version` after updating JDK.
