### ISSUE TITLE
希望能支持mysql后端

### ISSUE THREAD

**Issue by 306495389li** [hugegraph/hugegraph-tools#47]
现在工具不支持mysql后端的分片导出，mysql做后端的没办法升级新版图数据库

**Comment by zhoney** [comment]
@306495389li 暂时MySQL和Memory等不支持shard API的后端无法backup，要支持的话，需要修改server端代码，会在0.11中进行支持。

如果备份需求强烈，可以先参照[讨论](https://github.com/hugegraph/hugegraph/issues/777#issuecomment-562523175)自行基于client实现。

另外，近期在讨论在tools里封装一版分页获取的方式，弥补0.9到0.10的MySQL和Memory等后端无法备份、恢复和迁移的问题。如确定实现会及时告知。

**Comment by javeme** [comment]
在 [#974](https://github.com/hugegraph/hugegraph/pull/974) 中支持了MySQL和memory的shard，并在 #56 中进行了适配
