### ISSUE TITLE
hugegraph-tool中的dump 导出命令，总提示有问题？我已经再hugegraph中更改了serverip

### ISSUE THREAD

**Issue by jwdjqwyp** [hugegraph/hugegraph-tools#57]

**Comment by javeme** [comment]
@lxb1111 关注下这个问题
![image](https://user-images.githubusercontent.com/9625821/85254946-e5fd5b00-b493-11ea-9eed-10a343043804.png)

**Comment by zhoney** [comment]
@jwdjqwyp 请提供下具体的问题复现步骤

**Comment by lxb1111** [comment]
![image](https://user-images.githubusercontent.com/58289576/85267363-c1ab7980-b4a7-11ea-883a-28438f4b69fb.png)
执行的时候，首先需要根据业务重写CustomFotmater类，然后执行命令的时候，需要加上 全局变量 --url --graph 参数 @jwdjqwyp
