### ISSUE TITLE
Invalid mode "NONE" of graph 'hugegraph' for restore sub-command

### ISSUE THREAD

**Issue by javeme** [hugegraph/hugegraph-tools#59]
![image](https://user-images.githubusercontent.com/9625821/86328692-c1fdfe80-bc77-11ea-9a8b-b8d1451b1943.png)

clone from: https://groups.google.com/forum/#!topic/hugegraph/qRUGxg_BYPQ

**Comment by zhoney** [comment]
1. restore命令有两种模式：`merging`和`restoring`，需要根据自己的需求选择restore的模式。
2. 另一方面图有三种模式，NONE、MERGING和RESTORING，默认状态下是NONE模式，restore时，根据选用的restore模式，将图设置成对应的模式

更多资料可以参考官网对于[backup/restore的说明](https://hugegraph.github.io/hugegraph-doc/guides/backup-restore.html)
