### ISSUE TITLE
gremlin-schedule异步执行count()，导致studio与server无法连接，批量写入api调用失败。

### ISSUE THREAD

**Issue by tmljob** [hugegraph/hugegraph-tools#66]
【版本信息】
   Server 0.10.4
   Studio 0.10.0
   tools 1.4.0

【问题描述】
  gremlin-schedule异步执行如下语句：
  ./hugegraph gremlin-schedule -s "g.E().hasLabel('relyibai').count()"

数据量，根据返回的任务结果，如下：
Task info: {task_name=g.E().hasLabel('relyibai').count(), task_progress=0, task_create=1601349393637, task_status=success, task_update=1601350548763, task_result=[1000000], task_retries=0, id=20, task_type=gremlin, task_callable=com.baidu.hugegraph.api.job.GremlinAPI$GremlinJob, task_input={"gremlin":"g.E().hasLabel('relyibai').count()","aliases":{"hugegraph":"graph"},"bindings":{},"language":"gremlin-groovy"}}

异步任务运行期间，发现如下是问题：
1、因同时在通过 batch api接口加载数据，发现数据加载失败，与Server 响应超时。
2、为验证server是否正常，在studio 进行简单gremlin查询，g.V().limit(10)，报错无法查询。
在异步任务完成后，studio查询正常，重启启动批量入库任务，期间不再执行gremlin-schedule,批量入库正常结束。

日志信息：
1、server日志：
1862 九月 29, 2020 11:26:12 上午 org.glassfish.jersey.server.ServerRuntime$Responder writeResponse
1863 严重: An I/O error has occurred while writing a response message entity to the container output stream.
1864 org.glassfish.jersey.server.internal.process.MappableException: java.io.IOException: Connection is closed
1865         at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
1866         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
1867         at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
1868         at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
1869         at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
1870         at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
1871         at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
1872         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
1873         at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
1874         at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
1875         at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
1876         at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
1877         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
1878         at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
1879         at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
1880         at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384)
1881         at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
1882         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
1883         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
1884         at java.lang.Thread.run(Thread.java:748)
1885 Caused by: java.io.IOException: Connection is closed
1886         at org.glassfish.grizzly.nio.NIOConnection.assertOpen(NIOConnection.java:445)
1887         at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:677)
1888         at org.glassfish.grizzly.http.server.NIOOutputStreamImpl.write(NIOOutputStreamImpl.java:83)
1889         at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
1890         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
1891         at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2033)
1892         at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment2(UTF8JsonGenerator.java:1348)
1893         at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1295)
1894         at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:457)
1895         at com.fasterxml.jackson.databind.ser.impl.IndexedStringListSerializer.serializeContents(IndexedStringListSerializer.java:121)
1896         at com.fasterxml.jackson.databind.ser.impl.IndexedStringListSerializer.serialize(IndexedStringListSerializer.java:79)
1897         at com.fasterxml.jackson.databind.ser.impl.IndexedStringListSerializer.serialize(IndexedStringListSerializer.java:21)
1898         at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:416)
1899         at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1416)
1900         at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:940)
1901         at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:618)
1902         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
1903         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
1904         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
1905         at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
1906         at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
1907         at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
1908         ... 19 more
1909 Caused by: java.io.IOException: 断开的管道
1910         at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
1911         at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
1912         at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
1913         at sun.nio.ch.IOUtil.write(IOUtil.java:51)
1914         at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
1915         at org.glassfish.grizzly.nio.transport.TCPNIOUtils.flushByteBuffer(TCPNIOUtils.java:149)
1916         at org.glassfish.grizzly.nio.transport.TCPNIOUtils.writeCompositeBuffer(TCPNIOUtils.java:86)
1917         at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:129)
1918         at org.glassfish.grizzly.nio.transport.TCPNIOAsyncQueueWriter.write0(TCPNIOAsyncQueueWriter.java:106)
1919         at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:260)
1920         at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:169)
1921         at org.glassfish.grizzly.nio.AbstractNIOAsyncQueueWriter.write(AbstractNIOAsyncQueueWriter.java:71)
1922         at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleWrite(TCPNIOTransportFilter.java:126)
1923         at org.glassfish.grizzly.filterchain.TransportFilter.handleWrite(TransportFilter.java:191)
1924         at org.glassfish.grizzly.filterchain.ExecutorResolver$8.execute(ExecutorResolver.java:111)
1925         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
1926         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
1927         at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
1928         at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
1929         at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
1930         at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:890)
1931         at org.glassfish.grizzly.filterchain.FilterChainContext.write(FilterChainContext.java:858)
1932         at org.glassfish.grizzly.http.io.OutputBuffer.flushBuffer(OutputBuffer.java:1059)
1933         at org.glassfish.grizzly.http.io.OutputBuffer.write(OutputBuffer.java:709)
1934         ... 39 more
1935
1936 2020-09-29 11:26:14 2710681 [task-worker-2] [INFO ] org.apache.hadoop.hbase.client.AsyncRequestFutureImpl [] - #3, waiting for 883093  actions to finish on table: h     ugegraph:g_oe

2、批量数据加载报错日志

 2020-09-29 11:21:26.499[Thread-20] ERROR cn.encdata.cloud.graph.job.LoadDataJobHandler[49] Failed to load data.
257575 com.baidu.hugegraph.rest.ClientException: Failed to do request
257576         at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:128)
257577         at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:151)
257578         at com.baidu.hugegraph.rest.RestClient.post(RestClient.java:138)
257579         at com.baidu.hugegraph.api.graph.VertexAPI.create(VertexAPI.java:56)
257580         at com.baidu.hugegraph.driver.GraphManager.addVertices(GraphManager.java:83)

257588         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
257589         at java.lang.Thread.run(Thread.java:748)
257590 Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
257591         at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:496)
257592         at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:278)
257593         at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:753)
257594         at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
257595         at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
257596         at org.glassfish.jersey.internal.Errors.process(Errors.java:229)
257597         at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
257598         at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:752)
257599         at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
257600         at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:351)
257601         at com.baidu.hugegraph.rest.RestClient.lambda$post$1(RestClient.java:153)
257602         at com.baidu.hugegraph.rest.RestClient.request(RestClient.java:126)
257603         ... 13 common frames omitted
257604 Caused by: java.net.SocketTimeoutException: Read timed out
257605         at java.net.SocketInputStream.socketRead0(Native Method)
257606         at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
257607         at java.net.SocketInputStream.read(SocketInputStream.java:171)
257608         at java.net.SocketInputStream.read(SocketInputStream.java:141)
257609         at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
257610         at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
257611         at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
257612         at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
257613         at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
257614         at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
257615         at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
257616         at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
257617         at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
257618         at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
257619         at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
257620         at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
257621         at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
257622         at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
257623         at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
257624         at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
257625         at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:450)
257626         ... 24 common frames omitted

@javeme

**Comment by javeme** [comment]
@tmljob 看起来使用的是hbase后端，可能是存储资源竞争瓶颈导致超时

**Comment by tmljob** [comment]
是hbase后端，那这个该如何解决避免出现类似情况？

**Comment by javeme** [comment]
需要先定位一下超时的根源在哪里，才可以判断如何来避免。

**Comment by javeme** [comment]
需要先定位一下超时的根源在哪里，才可以判断如何来避免。
