### ISSUE TITLE
[问题 ] 图数据0.9/0.10版本升级0.11失败（点边数据不一致） 

### ISSUE THREAD

**Issue by DoubleBabylol** [hugegraph/hugegraph-tools#78]
### Expected behavior 期望表现
图数据0.9/0.10版本通过tools migrate升级至0.11版本 

### Actual behavior 实际表现
点数据可正确转换后导入（例如数值类型）
但边id未做相应的**转换**，导致点边id不匹配，例子见下：

### Steps to reproduce the problem 复现步骤
使用tools工具进行migrate,迁移完成后，使用gremlin查询同一点边，点id发生了变换，但是边id未变化，此时点为孤立点
- primary key模式下：旧点id  `1:37449855`  新点id  `1:5Es1~`

#### Vertex/Edge example 数据示例

1. 0.9版本点查询：g.V().hasLabel('file', 'network').has('uid', within(37449855,436342406))
![image](https://user-images.githubusercontent.com/48874214/103226914-202a4680-4968-11eb-8bd5-ab620728e5b8.png)

2. 迁移到0.11版本查询同一条gremlin：g.V().hasLabel('file', 'network').has('uid', within(37449855,436342406))
![35631609170989_ pic_hd](https://user-images.githubusercontent.com/48874214/103227017-5962b680-4968-11eb-866d-b11f126d8d68.jpg)

### Specifications of environment 环境信息
- hugegraph server version: 0.11
- hugegraph tool version: 1.5.0

@zhoney  @javeme

**Comment by zhoney** [comment]
@DoubleBabylol 
![image](https://user-images.githubusercontent.com/17330028/103536371-5bc79200-4ecd-11eb-8cfb-1fbe440048b7.png)

这个是迁移之后的图查询结果吗？这个系统中，查询一下 `file` VertexLabel的定义

![image](https://user-images.githubusercontent.com/17330028/103536429-7568d980-4ecd-11eb-8f3f-0dc55480d867.png)

这个是迁移之前旧的系统的查询结果吗？

@lxb1111 关注下这个问题，尝试复现

**Comment by DoubleBabylol** [comment]
你好 是这样的,点如1:52Es1~是迁移之后新版本的查询结果，这两张图是一个查询语句在新旧版本的结果。
- 这样就导致在我用tools从0.9版本导出边到0.11新版本图，边id中中包含的点id（sourceVertexId和targetVetxexId)仍然是1:37449855 ,但是实际这个点id是旧版本的点id，新版本不存在此id，点边无法关联起来。
- VertexLabel如下：
```
"vertexlabels": [
        {
            "id": 1,
            "name": "file",
            "id_strategy": "PRIMARY_KEY",
            "primary_keys": [
                "uid"
            ],
            "nullable_keys": [
                "date",
                "info",
                "ioc",
                "tags",
                "severity",
                "taskid"
            ],
            "index_labels": [
                "fileByType"
            ],
            "properties": [
                "uid",
                "type",
                "date",
                "info",
                "ioc",
                "tags",
                "severity",
                "taskid"
            ],
            "status": "CREATED",
            "ttl": 0,
            "enable_label_index": true,
            "user_data": {
                "~create_time": "2020-12-29 16:07:28.046"
            }
        },
```

**Comment by zhoney** [comment]
@DoubleBabylol 
明白你现在遇到的问题了。这是由于新版本对primary key是数字类型的时候进行了编码导致的。

我计划在HugeGraphServer端增加一个参数，控制primary key是否编码，在使用tools进行迁移时，server端这个配置项设置为false（不对primary key编码）即可保持映射。

你需要做的工作是换一个新的server包，并设置为不对primary key编码，进行迁移

**Comment by DoubleBabylol** [comment]
感谢作者 (❁´ω`❁)～

我的思路是vid不变，对edgeid中的vid也进行编码，来保持点边id一致，只是这样改动可能会多一些

**Comment by zhoney** [comment]
@DoubleBabylol 
是的，这个思路也是ok的。不过这个编码需要在tools里面做，需要tools根据顶点primary key找到顶点的id，然后再恢复边，恢复效率会低很多。

**Comment by DoubleBabylol** [comment]
好的 感谢作者
