### ISSUE TITLE
restore 图时出现exception, 只能恢复部分数据

### ISSUE THREAD

**Issue by chencjiajy** [hugegraph/hugegraph-tools#86]
hugegraph-tools: 1.4.0 
hugegraph: 0.10.4
后端：hbase 

backup的命令和summary如下， 其中split-size使用了默认的，直接将数据备份到了本地:

`./bin/hugegraph --url http://hugegraph:8181  --graph home backup -t all --directory ./backup-home`
>Graph 'home' start backup!
Property key backup started
Property key backup finished: 21
Vertex label backup started
Vertex label backup finished: 15
Edge label backup started
Edge label backup finished: 22
Index label backup started
Index label backup finished: 29
Vertices backup started
Vertices has been backup: 168115
Vertices backup finished: 168115
Edges backup started
Edges has been backup: 526578
Edges backup finished: 526578
>
>backup summary: {
	property key number: 21,
	vertex label number: 15,
	edge label number: 22,
	index label number: 29,
	vertex number: 168115,
	edge number: 526578,
}
>cost time(s): 19

设置图模式
`./bin/hugegraph --url http://hugegraph1:8183 --graph homeBak graph-mode-set -m RESTORING`
恢复图命令
`./bin/hugegraph --url http://hugegraph1:8183 --graph homeBak restore -t all --directory ./backup-home`
>Graph 'homeBak' start restore in mode 'RESTORING'!
Property key restore started
Property key restore finished: 21
Vertex label restore started
Vertex label restore finished: 15
Edge label restore started
Edge label restore finished: 22
Index label restore started
Index label restore finished: 29
Vertices restore started
Restoring VERTEX ...
files: [
	vertices1.zip,
	vertices2.zip,
	vertices3.zip,
	vertices0.zip,
]
Vertices has been restored: When restoring vertices in file 'vertices0.zip' occurs exception 'com.baidu.hugegraph.exception.ToolsException: Exception occurred while restoring vertices(after 3 retries)'
When restoring vertices in file 'vertices2.zip' occurs exception 'com.baidu.hugegraph.exception.ToolsException: Exception occurred while restoring vertices(after 3 retries)'
85197
Vertices restore finished: 85197
Edges restore started
Restoring EDGE ...
files: [
	edges0.zip,
	edges1.zip,
	edges2.zip,
	edges3.zip,
]
Edges has been restored: When restoring edges in file 'edges1.zip' occurs exception 'com.baidu.hugegraph.exception.ToolsException: Exception occurred while restoring edges(after 3 retries)'
When restoring edges in file 'edges0.zip' occurs exception 'com.baidu.hugegraph.exception.ToolsException: Exception occurred while restoring edges(after 3 retries)'
159881
Edges restore finished: 159881
>
>restore summary: {
	property key number: 21,
	vertex label number: 15,
	edge label number: 22,
	index label number: 29,
	vertex number: 85197,
	edge number: 159881,
}
cost time(s): 57

想问一下是因为什么原因导致了exeption呢？ 如何去解决

**Comment by imbajin** [comment]
这里看不到具体的报错信息, 表面看就是读从 hbase 里到导出数据然后导入时失败了, 并且重试也没成功. 

你可以看看日志里还有详细的报错信息么?  如果具体的异常被吞了, 你可以尝试用 [Arthas](https://arthas.aliyun.com/doc/watch.html#id7) 的 `watch -e` 观测 exception 抛出, 可以捕获具体异常信息.

最后以上都不行的话, 你可以检查一下你的导出数据是否完整正确, 然后提供一下复现的方式么?

**Comment by chencjiajy** [comment]
我执行的顺序就如问题描述里执行的，基本每次运行都会报异常， 因为这个[issue](https://github.com/hugegraph/hugegraph-tools/issues/81)  使用hugegraph tools 1.5.0在使用server 0.10.4时会报错，才使用hugegraph toos 1.4.0来备份和恢复的


用Arthas 我怎么去观测异常呢，你能告诉我怎么写命令吗？我使用`watch com.baidu.hugegraph.cmd.HugeGraphCommand execute "{params[0],throwExp}" -e -x 2` 和`watch com.baidu.hugegraph.manager.RestoreManager  restoreVertices "{params,throwExp}" -e -x 3`捕获不到异常

![image](https://user-images.githubusercontent.com/19321967/116642768-2bd35b80-a9a2-11eb-86c6-4cb9e22fef91.png)

![image](https://user-images.githubusercontent.com/19321967/116648257-29c3c980-a9af-11eb-86d2-64ad86560ce5.png)

**Comment by javeme** [comment]
> 因为这个[issue](https://github.com/hugegraph/hugegraph-tools/issues/81) 使用hugegraph tools 1.5.0在使用server 0.10.4时会报错，才使用hugegraph toos 1.4.0来备份和恢复的

@imbajin 如果暂时无法复现此问题解决，可以基于fix了的client打包下tools传到#81中。
