### ISSUE TITLE
[Bug]为什么使用hugegraph tool 备份的数据，比直接查询的数据要少

### ISSUE THREAD

**Issue by 18252054238** [hugegraph/hugegraph-tools#89]
版本： hugegraph-tools-1.5.0 hugegraph-0.11.2

查询语句：
```bash
sh bin/hugegraph  --url http://127.0.0.1:8180 --graph hugegraph3 gremlin-execute --script "g.V().hasLabel('post').count()"
Run gremlin script
1237554
```

备份语句：
```
sh bin/hugegraph  --url http://127.0.0.1:8180 --graph hugegraph3 backup --format text  --label post --compress false -d backup10 -t vertex --properties imagefile,creationdate,content,locationip
Graph 'hugegraph3' start backup!
Vertices backup started
Vertices has been backup: 1237542
Vertices backup finished: 1237542
===============================================
backup summary: {
        property key number: 0,
        vertex label number: 0,
        edge label number: 0,
        index label number: 0,
        vertex number: 1237542,
        edge number: 0,
}
cost time(s): 58
```

**Comment by imbajin** [comment]
看起来相差的数目很少, 有两个方法帮助确定一下: (更新参考下方 `limit(-1)` 确认一下)
- 100多万个点的 id 存储为两个文件, 对比一下缺失的项. 然后确认一下数据是否有问题
- 切分导出的文件大小, 分批导入, 然后看看是哪个范围内的点缺失了, 进一步二分缩小范围, 看看是否可以找到确认的点

如果可以稳定复现, 那就是 bug 这样也能提供具体的 case 来供复现使用, 单纯说少了数据, 不好定位是哪的问题.

**Comment by javeme** [comment]
@18252054238 可以使用limit(-1)来精确的查询count：`g.V().hasLabel('post').limit(-1).count()`。如果还不一致，请提供下版本号、后端存储、复现流程等信息。

**Comment by 18252054238** [comment]
@javeme 
精确查询确实和backup得到的数量一致。
我是用文本导入的，3个vertex，2个edge，我去查了一下没有正确导入的数据本身是没有问题的（格式正确，没有重复id）。我去试了一下，如果我只单独导入那个有问题的点的数据，在备份出来就不会出现这个问题，请问这有什么可能原因吗？

Task info: {task_name=g.V().hasLabel('post').limit(-1).count(), task_progress=0, task_create=1623138878419, task_status=success, task_update=1623138917217, task_result=[1237542], task_retries=0, id=1, task_type=gremlin, task_callable=com.baidu.hugegraph.job.GremlinJob, task_input={"gremlin":"g.V().hasLabel('post').limit(-1).count()","aliases":{"hugegraph3":"graph"},"bindings":{},"language":"gremlin-groovy"}, task_server=server-1}

**Comment by 18252054238** [comment]
找到原因了，数据导入的时候，在不同label下，如果有相同的uid也会冲突。
