### ISSUE TITLE
想请问一下使用hugegraph-tool做备份的时候，是不是不能把数据备份到开启kerberos的hdfs上？

### ISSUE THREAD

**Issue by 18252054238** [hugegraph/hugegraph-tools#90]
想请问一下使用hugegraph-tool做备份的时候，是不是不能把数据备份到开启kerberos的hdfs上？

**Comment by imbajin** [comment]
默认应该缺乏 `kerberos` 的一些配置文件和参数把, 你可以参考 loader 的[支持方式](https://github.com/hugegraph/hugegraph-loader/pull/176/files)简单适配一下.

另外就是先备份到本地在上传 hdfs 了

**Comment by 18252054238** [comment]
@imbajin 感谢解惑。
