### ISSUE TITLE
导出的时候属性是以逗号分隔，是否有参数可以更换分隔符？string类型的属性在导出的时候是否可以加上引号？

### ISSUE THREAD

**Issue by 18252054238** [hugegraph/hugegraph-tools#91]
导出的时候属性是以逗号分隔，是否有参数可以更换分隔符？string类型的属性在导出的时候是否可以加上引号？

**Comment by imbajin** [comment]
分隔符可能可以配置, 你可以参考一下代码和文档 (但不确定)
后者默认应该没有, 这种比较特定的需求, 建议自己改一下源码相关导出的地方, 可能就几行就能实现了
